name: 单元测试流程

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出项目
        uses: actions/checkout@v3

      - name: 使用JDK 17 环境
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: 执行单元测试
        run: |
          chmod +x ./gradlew
          ./gradlew test

      - name: 上传产出物(测试报告)
        uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ./**/build/reports/**